<script setup lang="ts">
import { ref, computed } from 'vue';
import { useTemplate } from '../composables/useTemplate';

const props = defineProps<{
  visible: boolean;
}>();

const emit = defineEmits<{
  close: [];
}>();

const { name, template, exportToml, anchorDate } = useTemplate();

const format = ref<'toml' | 'bash'>('toml');
const startDate = ref(anchorDate.value);
const copySuccess = ref(false);

const LEVEL_COMMITS = [0, 2, 8, 16, 25];

const slugifiedName = computed(() => {
  return name.value
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    || 'template';
});

function generateBash(): string {
  const lines: string[] = [
    '#!/usr/bin/env bash',
    '# Generated by contriband editor',
    '# Usage: bash contriband-apply.sh /path/to/repo',
    '',
    'set -euo pipefail',
    'REPO="${1:?Usage: $0 /path/to/repo}"',
    'cd "$REPO"',
    '',
  ];

  const start = new Date(startDate.value + 'T00:00:00');
  const grid = template.value.grid;

  for (let col = 0; col < template.value.width; col++) {
    for (let row = 0; row < 7; row++) {
      const level = grid[row]?.[col] ?? 0;
      if (level === 0) continue;
      const commits = LEVEL_COMMITS[level] ?? 0;
      if (commits === 0) continue;

      const date = new Date(start);
      date.setDate(date.getDate() + col * 7 + row);
      const dateStr = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;

      lines.push(`# ${dateStr}: level ${level}, ${commits} commits`);
      lines.push(`for i in $(seq 1 ${commits}); do`);
      lines.push(`  echo "${dateStr}T12:$((i*5)):00Z pixel level=${level} commit=$i" >> contriband.log`);
      lines.push('  git add contriband.log');
      lines.push(`  GIT_AUTHOR_DATE="${dateStr}T12:$((i*5)):00+0000" \\`);
      lines.push(`  GIT_COMMITTER_DATE="${dateStr}T12:$((i*5)):00+0000" \\`);
      lines.push(`  git commit -m "contribart: pixel at ${dateStr} (level ${level}, commit $i/${commits})"`);
      lines.push('done');
      lines.push('');
    }
  }

  return lines.join('\n');
}

const exportContent = computed(() => {
  return format.value === 'toml' ? exportToml() : generateBash();
});

function download() {
  const ext = format.value === 'toml' ? '.toml' : '.sh';
  const type = 'text/plain';
  const blob = new Blob([exportContent.value], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${slugifiedName.value}${ext}`;
  a.click();
  URL.revokeObjectURL(url);
}

async function copyToClipboard() {
  try {
    await navigator.clipboard.writeText(exportContent.value);
    copySuccess.value = true;
    setTimeout(() => (copySuccess.value = false), 2000);
  } catch (e) {
    console.error('Failed to copy:', e);
  }
}
</script>

<template>
  <div v-if="visible" class="export-dialog">
    <div class="dialog-header">
      <span class="dialog-title">Export Template</span>
      <button class="dialog-close" @click="emit('close')">&times;</button>
    </div>

    <div class="mb-3">
      <label class="label">Template name</label>
      <input v-model="name" type="text" class="input" placeholder="my-design" />
    </div>

    <div class="format-toggle mb-3">
      <button
        class="toggle-btn"
        :class="{ active: format === 'toml' }"
        @click="format = 'toml'"
      >TOML</button>
      <button
        class="toggle-btn"
        :class="{ active: format === 'bash' }"
        @click="format = 'bash'"
      >Bash Script</button>
    </div>

    <div v-if="format === 'bash'" class="mb-3">
      <label class="label">Start date</label>
      <input v-model="startDate" type="date" class="input" />
    </div>

    <div class="flex gap-2">
      <button
        class="btn flex-1"
        :class="copySuccess ? 'btn-primary' : 'btn-secondary'"
        @click="copyToClipboard"
      >
        {{ copySuccess ? 'Copied!' : 'Copy' }}
      </button>
      <button class="btn btn-primary flex-1" @click="download">
        Download
      </button>
    </div>

    <p v-if="format === 'bash'" class="hint">
      After running the script:<br>
      <code>cd /path/to/repo && git push</code>
    </p>
  </div>
</template>

<style scoped>
.export-dialog {
  position: absolute;
  top: 100%;
  right: 0;
  margin-top: 8px;
  padding: 16px;
  background: var(--color-card);
  border: 1px solid var(--color-border);
  border-radius: 12px;
  box-shadow: var(--shadow-lg);
  min-width: 300px;
  z-index: 100;
}

.dialog-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12px;
}

.dialog-title {
  font-size: 14px;
  font-weight: 600;
  color: var(--color-text);
}

.dialog-close {
  background: none;
  border: none;
  font-size: 18px;
  color: var(--color-text-muted);
  cursor: pointer;
  padding: 0 4px;
  line-height: 1;
}

.dialog-close:hover {
  color: var(--color-text);
}

.mb-3 {
  margin-bottom: 12px;
}

.format-toggle {
  display: flex;
  gap: 2px;
  padding: 2px;
  background: var(--color-bg);
  border-radius: 8px;
}

.toggle-btn {
  flex: 1;
  padding: 6px 12px;
  font-size: 13px;
  font-weight: 500;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  background: transparent;
  color: var(--color-text-muted);
  transition: all 0.15s ease;
}

.toggle-btn.active {
  background: var(--color-card);
  color: var(--color-text);
  box-shadow: var(--shadow-sm);
}

.flex {
  display: flex;
}

.flex-1 {
  flex: 1;
}

.gap-2 {
  gap: 8px;
}

.hint {
  margin-top: 12px;
  font-size: 12px;
  color: var(--color-text-muted);
  line-height: 1.5;
}

.hint code {
  display: inline-block;
  margin-top: 4px;
  padding: 2px 6px;
  background: var(--color-bg);
  border: 1px solid var(--color-border);
  border-radius: 4px;
  font-size: 11px;
  font-family: monospace;
}
</style>
